---
platformsh:
  project_name: ''
  project_id: ''
  project_environment: 'master'
vagrantfile:
  vm:
    hostname_base: 'platformsh.dev'
    memory: '2048'
    cpus: '2'
    network:
      private_network: 10.22.22.100
